# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install only prod dependencies later; build requires devDeps
RUN npm install --ignore-scripts && \
    npm run build && \
    npm prune --production

# Copy any remaining files
# (if needed for runtime; dist already created above)

# Set environment
ENV NODE_ENV=production

# Start the MCP server
CMD ["node", "dist/index.js"]
